### ISSUE TITLE
Test the app before uploading to DockerHub

### ISSUE THREAD

**Issue by itayf9** [Danielsio/Plan-IT-Web#42]
The current situation is, that when ever a pull request it created or any brunch is being merged to the `master`, the `build-docker-image.yml` workflow is running, therefore uploading the image to DockerHub. We need to prevent a situation where we upload a non-working version to DockerHub.
Thus, need to test the app before uplaoding to DockerHub.

There are two ways to do that:
- Add a new "test" job to `build-docker-image.yml` workflow, which will be activated before "upload" and after "build".
- Split the workflow into two workflows. One will build and test and will be triggered by pull requests. The other one will build and push and will be triggered by push to `master`.

**Comment by Danielsio** [comment]
i think option 2 makes more sense to me

**Comment by Danielsio** [comment]
notice those issue already exist #34 #35

**Comment by Danielsio** [comment]
this issue can be closed since there is no need to build docker image anymore
