### ISSUE TITLE
Fix UI in home page - better looking for it

### ISSUE THREAD

**Issue by itayf9** [Danielsio/Plan-IT-Web#56]
Need to redesign the home page.
Maybe add a background, and consider removing/rewriting the paragraph over there, or add some pictures of the calendar before and after the usage.

**Comment by oshriFadlon1** [comment]
I'm thinking about adding this background
![image](https://github.com/Danielsio/Plan-IT-Web/assets/102179412/62b55d6c-02c3-46e3-a449-92c81d967f42)

In addition I will take the summry we worte, or I will make it to by a flip card that contain picture before and after.

**Comment by Danielsio** [comment]
is this issue still relevent ? or we are working only on DarkMode now ?

**Comment by oshriFadlon1** [comment]
we work now on the dark mode

**Comment by itayf9** [comment]
This is a duplicated issue, we will work only on #69
