### ISSUE TITLE
Fix UX in generate page - the regeneration process

### ISSUE THREAD

**Issue by itayf9** [Danielsio/Plan-IT-Web#58]
Need to think of a way to make the regeneration process clear to the user.
Need to distinguish it from the "new generation". As of now, the "new generation" is below the textfields "start" and "end" which are related to it. But we need to attach the "regeneration" button to the latest study plan, and espacially to the latest "start" and "end".

**Suggestions:**
1. Put the "Regenerate" button in the "Generated study plan" section (where all the relevent info is already available).
2. Keep the "Regenerate" button in the same section of the "New Generate" stuff, but insert the latest "start" and "end" next to it.
3. Create a new section (probably above the "New Generate" section), that will contain the "Regenerate" buttons, dates and a small explaination.

**Comment by Danielsio** [comment]
i will start working on option 1
