### ISSUE TITLE
No "course ID" in the courseItem and in "edit course"

### ISSUE THREAD

**Issue by itayf9** [Danielsio/Plan-IT-Web#75]
There is no "course ID" field in the `courseItem` component which is displayed on `AdminCoursesDashboard`.
Also, you cannot change the "course ID" from the "edit course" page. Is it a bug or a feature?

**Comment by Danielsio** [comment]
i can fix that, but does it really matter ?

**Comment by itayf9** [comment]
In my opinion, the admin dashboard should act like a GUI to the DB, so yes I think it's important.

**Comment by itayf9** [comment]
I've handled that issue in #78
